run:
  skip-files: []
linters:
  enable-all: true
  disable:
  - depguard
  - dupl
  - execinquery
  - exhaustruct
  - funlen
  - gochecknoinits
  - gomnd
  - paralleltest

  # linters deprecated
  - deadcode
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - nosnakecase
  - maligned
  - scopelint
  - structcheck
  - varcheck