version: '3'

tasks:
  default:
    cmds:
      - go generate ./...
      - sqlc generate
      - gofmt -w .
      - deno fmt README.md
      - golangci-lint run --fix --timeout "10m"
      - go test -cover -race ./...
      - go build ./...